package online.weiyin.mapper;

import online.weiyin.pojo.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper //mybatis提供的注解，类似于@Repository，可以将该接口注册成bean
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jan 11 10:53:49 CST 2023
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jan 11 10:53:49 CST 2023
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jan 11 10:53:49 CST 2023
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jan 11 10:53:49 CST 2023
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jan 11 10:53:49 CST 2023
     */
    int updateByPrimaryKey(Student record);
}