package online.weiyin.pojo;

import java.util.Date;

public class AccountLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_log.id
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_log.message
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_log.happen_time
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    private Date happenTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_log.id
     *
     * @return the value of t_account_log.id
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_log.id
     *
     * @param id the value for t_account_log.id
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_log.message
     *
     * @return the value of t_account_log.message
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_log.message
     *
     * @param message the value for t_account_log.message
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_log.happen_time
     *
     * @return the value of t_account_log.happen_time
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public Date getHappenTime() {
        return happenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_log.happen_time
     *
     * @param happenTime the value for t_account_log.happen_time
     *
     * @mbg.generated Wed Jan 11 16:15:16 CST 2023
     */
    public void setHappenTime(Date happenTime) {
        this.happenTime = happenTime;
    }
}